# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'HKBanner-Samples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HKBanner-Samples
  
  # R.Swift
  pod 'R.swift'

  # Networking
  pod 'Alamofire'
  # ImageCache
  pod 'Kingfisher'
  # AutoLayout
  pod 'SnapKit'

  pod 'HKBanner', :path => '../'

  # 项目框架
  pod 'Comet'
  # 菊花
  pod 'Chrysan'

end
